### ISSUE TITLE
Allow facet_multiple to output a single page at a time

### ISSUE THREAD

**Issue by daattali** [guiastrennec/ggplus#10]
It'd be great if facet_multiple accepted a parameter "page" which is a number (NULL by default). If it's NULL then it outputs all pages, as it does now. But if it's a number, then only output that page. This way it'd be easy to incorporate it into shiny with an ability to paginate through pages of plots

**Comment by guiastrennec** [comment]
This is a great idea, I will add this functionality in the next update of ggplus. Do you think it would be of any use to have the possibility to provide a numeric vector to page in order to print several pages at once?

**Comment by daattali** [comment]
I personally think it doesn't make too much sense, but I see no harm in it.
Having single pages means I can add pagination buttons to  a shiny app.
It'd also be nice if the output could be returned as an object rather than
being printed and lost

**Comment by guiastrennec** [comment]
I agree that being able to return a ggplot2 object rather than printing would be extremely convenient. However in order to maintain the desired layout on the last page (even in the case where they are empty rows), the ggplot2 object needs to be converted grobs which are then edited. This is not straight forward but this is unfortunately the only way I could find. All suggestions are welcome.

**Comment by daattali** [comment]
I see. I don't have any advice, if you think it's hard then I trust you :)

I agree that being able to return a ggplot2 object rather than printing
would be extremely convenient. However in order to maintain the desired
layout on the last page (even in the case where they are empty rows), the
ggplot2 object needs to be converted grobs which are then edited. This is
not straight forward but this is unfortunately the only way I could find.
All suggestions are welcome.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/guiastrennec/ggplus/issues/10#issuecomment-249452427>,
or mute the thread
