### ISSUE TITLE
ggplus facet multiple will not run on radar charts

### ISSUE THREAD

**Issue by real-quantdog** [guiastrennec/ggplus#13]
I am trying to separate my radar graphs using facet_multiple. It will not let me do multiple pages. If I put any less rows then the total rows in the data set then the code will not work. I get this error:

Error in scale_transform(scale, limits) : 
  could not find function "scale_transform"

I am not sure why this is doing this. Here is my ggplot2 code. 

both_graph <- both %>%
  gather(key, value, team , self) %>%
  ggplot( aes(x  = reorder(Value, orderz), y = value, fill=key ) ) +  theme_light() +
  geom_polygon(aes(group = key, color = key),
               fill  = NA , size = 1) +
#  facet_wrap(~ ResponseId, ncol=1) +
  ylim(0, 5) +
  ggtitle("Manager Results: Team vs. Self") +
  theme(strip.text.x = element_text(color="black", size=rel(0.5), vjust=0.5),
        axis.text.x  = element_text(size = rel(0.5)),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  guides(fill=TRUE, color = "none")+
  xlab("") + ylab("") +
  coord_radar()
 both_graph <- facet_multiple(plot = both_graph,
               facets = 'ResponseId',
               ncol = 2,
               nrow = 2)

**Comment by real-quantdog** [comment]
ggforce works in ggplot 2.2 but ggplus doesn't work.

**Comment by HedvigS** [comment]
I'm having the same problem as well, now in 2019. Is there any news on the compatibility of ggplot and ggplus?

**Comment by guiastrennec** [comment]
@HedvigS as mentioned in #12 ggplus is no longer compatible with the most recent versions of ggplot. As an alternative I suggest that you use the very good [`facet_wrap_paginate()`](https://ggforce.data-imaginist.com/reference/facet_wrap_paginate.html) or [`facet_grid_paginate()`](https://ggforce.data-imaginist.com/reference/facet_grid_paginate.html) from the [`ggforce`](https://ggforce.data-imaginist.com/) package. I updated the ggplus readme page to better reflect this.

**Comment by HedvigS** [comment]
Thanks @guiastrennec . I tried those in the end and they worked, kind of. Oh well
