### ISSUE TITLE
Problem with facet_multiple() when both ncol and nrow = 1

### ISSUE THREAD

**Issue by kkl234** [guiastrennec/ggplus#2]
I recently ran facet_multiple for to plot ~25 graphs. It worked great as long as ncol or nrow was >1. But if I set both ncol and nrow = 1, the last graph never properly displayed. Instead the strip was always labeled "ghost=0" and there was no data in the graph.

**Comment by guiastrennec** [comment]
Thank you for your interest in ggplus. I am curious when you use ncol and nrow = 1 do you want to get a panel type plot or a regular ggplot?

**Comment by kkl234** [comment]
I'm looking to produce a regular ggplot, but with only 1 plot per page.

**Comment by guiastrennec** [comment]
The problem should be fixed now

**Comment by kkl234** [comment]
Just reinstalled and tried it; works perfectly. Thanks for fixing!
