### ISSUE TITLE
Package not for MacOS

### ISSUE THREAD

**Issue by Slyrs** [guiastrennec/ggplus#6]
Thank you very much for this interesting package - which I would lve to use. Unfortunately one cannot install it on a mac form your source. One gets the error:

Error in install.packages : cannot install Windows binary packages on this platform

Is there any possibility to install on a mac?
Thanks!

**Comment by guiastrennec** [comment]
Hello Slyrs,
Thank you very much for your interest in ggplus. I am using a mac and I am able to install the package without any issues using the following command in R:
`devtools::install_github("guiastrennec/ggplus")`
Make sure you have updated the package devtools and your version of R and it should work.

Best

**Comment by Slyrs** [comment]
Installation works like a charm! Thank you! I forgot to install devtools at this machine :-(
