### ISSUE TITLE
documentation is confusing for a newbie

### ISSUE THREAD

**Issue by jpmorris** [guiastrennec/ggplus#7]
The markdown instructions say that you can use facet_multiple to 'split pannels over multiple pages', then later in 'plot multiple pages using marrangegrob' it says marrangegrob can be used to 'split the grobs over multiple pages'.   

I would just like to produce a pdf with the facets of the plots spanning the pages of the pdf.  But it's not clear to me if I can use facet_multiple() to do this. The only mention of the pdf writer is in mArrangeGrob(), but it's not clear to me if this is an alternative method or that I just shouldn't be using facet_multiple() (which doesn't seem to work with the same pdf code found in mARrangeGrob()).  What is the relation of facet_multiple() (which is introduced first in the documentation) to mArrangeGrob()?

**Comment by jpmorris** [comment]
So my mistake seems to be trying to do:

multi.plot <- facet_multiple(plot = p, facets = 'somevar', ncol = 1, nrow = 4)

as opposed to
pdf('my.pdf', w = 12, 8)
facet_multiple(plot = p, facets = 'somvar, ncol = 2, nrow = 6)
dev.off()

which seems to work.  I still think the documentation can be improved slightly, however.

**Comment by guiastrennec** [comment]
Thanks for the feedback, I will update the documentation to make the export to PDF more clear.
