### ISSUE TITLE
Not compatible with newer versions of R

### ISSUE THREAD

**Issue by akitepowell** [guiastrennec/ggplus#8]
Hi,

I think the facet_multiple function in this package will solve a major problem for me, and was wondering if there were plans to make this package compatible with the latest versions of R.  
Thanks,
Aaron

**Comment by guiastrennec** [comment]
Dear Aaron,

I apologize for the state of the package ggplus, I wish I had more time to update it more frequently. Thank you for bringing this issue to my attention but could you provide me with more details regarding your version of R? And the problem you encounter (possibly a reproductible example)

I am using ggplus daily with R 3.3.0 and it works fine for me

**Comment by akitepowell** [comment]
Hi,

Ok.  I'm using 3.3.1, and when I try to load it I get the following message:
Warning in install.packages :
  package ‘ggplus’ is not available (for R version 3.3.1)

Thanks,
Aaron

**Comment by guiastrennec** [comment]
Okay I was able to reproduce your issue, the package is only available on github so if your try to install it with the regular install package: `install.packages('ggplus')` you will get the error:
```Warning in install.packages :
  package ‘ggplus’ is not available (for R version 3.3.1)```

You should instead use the following command to install it from github and it should work:
`devtools::install_github("guiastrennec/ggplus")`

**Comment by akitepowell** [comment]
Ah, ok that worked.  Sorry, I'm a little new to this work.  I will now try to figure out how to get ggplus to work for me.  I really like working with facets in ggplot2, but wanted a good way to have multiple pages of facets.  I think ggplus should work, but I may have some questions.
Thanks,
Aaron

**Comment by guiastrennec** [comment]
Great I will close this issue then
