### ISSUE TITLE
facet_multiple scales = "free" question

### ISSUE THREAD

**Issue by akitepowell** [guiastrennec/ggplus#9]
Is it possible to set the y axis scales to free when using the facet_multiplot function?  I've tried:

facet_multiple(plot=p, facets = "Reporting.Area",scales="free", ncol=4, nrow=4)

but this doesn't seem to work.
Thanks,
Aaron

**Comment by guiastrennec** [comment]
Hello Aaron,

Yes it should work as in `ggplot2`, you can try the following code and you will see that each panel will have its own y axis with different limits depending on the data.
```r
p <- ggplot(mtcars, aes(x = wt, y = hp)) +
  geom_point()

# To have x and y free
facet_multiple(plot = p, facets = 'carb', scales = 'free', ncol = 2, nrow = 2)

# To only have y free
facet_multiple(plot = p, facets = 'carb', scales = 'free_y', ncol = 2, nrow = 2)
```
